#has all css selectors for web scraping
#imported by stats_page.py

inflation_guru = "#__next > div.css-6lpq93 > div > div.css-1az6hu7 > div.card.css-vdvsua > div > p"
inflation_ping = "#app > div > div > div.xl\:\!ml-64.px-3.pt-4 > div:nth-child(2) > div > div.grid.grid-cols-1.gap-4.md\:\!grid-cols-3.lg\:\!grid-cols-6.mt-4 > div:nth-child(5) > div > div:nth-child(2) > h6"
osmosis1_ = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(1) > div.px-.flex.items-center.justify-start.py-4.md\:px-6.lg\:px-0 > div:nth-child(1) > div > span.text-20.nls-font-500.text-primary"
osmosis2_ = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(1) > div.px-.flex.items-center.justify-start.py-4.md\:px-6.lg\:px-0 > div:nth-child(1) > div > span.text-16.nls-font-500.text-primary"
osmosis_util = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(1) > div.border-standart.block.border-b > div > div > div > div > span.text-28.nls-font-500.text-primary"

neutron1_ = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(2) > div.px-.flex.items-center.justify-start.py-4.md\:px-6.lg\:px-0 > div.pt-3.lg\:pl-4 > div > span.text-20.nls-font-500.text-primary"
neutron2_ = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(2) > div.px-.flex.items-center.justify-start.py-4.md\:px-6.lg\:px-0 > div.pt-3.lg\:pl-4 > div > span.text-16.nls-font-500.text-primary"
neutron_util = "#app > div > div.custom-scroll.flex.w-full.flex-1.justify-center.pb-20.pt-20.lg\:ml-\[210px\].lg\:pb-8 > div > div > div.background.border-standart.shadow-box.mt-6.flex.max-w-\[100\%\].flex-col.outline.md\:flex-row.lg\:rounded-xl > div:nth-child(2) > div.border-standart.block.border-b > div > div > div > div > span.text-28.nls-font-500.text-primary"